version: '2'
services:
        edgeimpulse-inference:
                build: ./edgeimpulse-inference
                restart: always 
        balena-cam:
                build: ./balena-cam
                privileged: true
                restart: always
                depends_on:
                        - edgeimpulse-inference
                ports:
                        - "80"
                labels:
                        io.balena.features.kernel-modules: '1'
        wifi-connect:
             image: balenablocks/wifi-connect:rpi
             restart: always
             network_mode: host
             privileged: true
             labels:
             io.balena.features.dbus: "1"
             io.balena.features.firmware: "1"
